export const routes = {
  home: "/",
  login: "/dang-nhap",
  register: "/dang-ky",
  forgot: "/quen-mat-khau",
  faq: "/faq",
  size: "/huong-dan-do-ni",
  bst: "/bo-suu-tap",
  blog: "/kien-thuc",
  sale: "/chuong-trinh-khuyen-mai",
  profile: "/trang-ca-nhan",
  about: "/ve-chung-toi",
  chain: "/huong-dan-do-vong-co",
  kienthuc: "/kien-thuc-kim-cuong",
  accessoryInfor: "/kien-thuc-trang-suc",
  warrantyPolicy: "/chinh-sach-bao-hanh",
  adminProduct: "/admin-san-pham",
  adminDiamond: "/admin-kim-cuong",
  adminAdd: "/admin-them-san-pham",
  changePassword: "/doi-mat-khau",
  adminmanageorder: "/admin-quan-li-don-hang",
  adminCategory: "/admin-danh-muc",
  adminUser: "/admin-user",
  tracking: "/theo-doi-don-hang",
  saleproduct: "/san-pham-giam-gia",
};
