export const routes = {
  home: "/",
  login: "/dang-nhap",
  register: "/dang-ky",
  forgot: "/quen-mat-khau",
  faq: "/faq",
  size: "/huong-dan-do-ni",
  bst: "/bo-suu-tap",
<<<<<<< Updated upstream

  blog: "/kien-thuc",
  sale: "/chuong-trinh-khuyen-mai",
  profile: "/trang-ca-nhan",
  about: "/ve-chung-toi",
  chain: "/huong-dan-do-vong-co",
  kienthuc: "/kien-thuc-kim-cuong",
  accessoryInfor: "/kien-thuc-trang-suc",
  warrantyPolicy: "/chinh-sach-bao-hanh",
  adminProduct: "/admin-san-pham",
  adminDiamond: "/admin-kim-cuong",
  adminStatistics: "/admin-thong-ke",
  adminCategory: "/admin-danhmuc",
=======
  admin: "/admin",
  blog: "/blog",
  sale: "/sale",
  profile: "/profile",
  about: "/about",
  chain: "/chain",
  kienthuc: "/kien-suc-trang-suc",
  accessoryInfor: "/accessoryinfor",
  warrantyPolicy: "/warrantypolicy",
  // statistics: "/statistics",
>>>>>>> Stashed changes
};
